# Change these first
owner: soumendrasaha # Your GitHub organization or username, where this repository lives
repo: upptimenew # The name of this repository


sites:
  - name: Google
    url: http://google.com/
  - name: GetDocSocks-Test
    url: https://www.getdocsocks.com/test-upptime

status-website:
  baseUrl: /upptimenew # where "repo" is your repository name
  name: Real Steve- Website Status


workflowSchedule:
  uptime: "*/5 * * * *"
